version: '3'

services:
  expensetracker:
    build: 
      context: .
      dockerfile: Dockerfile
    image: expensetracker-docker
    container_name: expensetracker
    restart: always # restart docker if stops
    ports:
      - "${PORT}:${PORT}"
    # working_dir: /var/www/expensetracker
    environment:
      MONGODB: ${MONGODB}
      PORT: ${PORT}